### ISSUE TITLE
Uncertain copyright status of eggplant image.

### ISSUE THREAD

**Issue by 20kdc** [XeonSquared/EggplantImage#1]
The eggplant image used appears to be a (possibly modified) version of the one in Apple iOS 9.
This may cause copyright issues regarding profile pictures run through the tool, and is also a misrepresentation of the source of the eggplant image in use.
People who run their profile pictures through this tool may be expecting unencumbered results - and this is not the case.

**Comment by XeonSquared** [comment]
You raise an interesting point, however, bitmap representations of scalable fonts have uncertain copyright status already, so I added a disclaimer to the README.
